[package]
name = "yazi-portal-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
smol = "2"

zbus = { version = "5", default-features = false, features = ["async-io"] }

config = { version = "0.15", default-features = false, features = ["toml"] }
serde = { version = "1", features = ["derive"] }
dirs = "6.0.0"
